version: "2"

services:

  wordpress:
    image: trytynichenko/wp-front
    ports:
      - "8080:80"
    links:
      - mysql:mysql
    volumes:
      - ./composer.json:/var/www/html/composer.json
      - ./log:/var/log/apache2
    environment:
      WP_WEBSITE_URL: wp.dev
      WP_WEBSITE_PORT: 8080

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dumps:/docker-entrypoint-initdb.d
